const vibrations = [
  'Writing an email',
  'Having just sent an email',
  'In supermarkets',
  'When children scream',
  'The morning after she has gone to the pub with friends',
  'The bus home when she has gone to the pub with friends',
  'When she says something in a group after having not spoken for more than 10 minutes',
  'When entering a new building',
  'When her phone rings',
  'Calling someone',
  'In supermarkets',
  'Whenever she sees a live fish.',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'Feeling full',
  'Feeling too hungry',
  'Waiting for food longer than expected',
  'Having to make conversation when hungry and anticipating food',
  'That loud noise the tube makes',
  'The sound of an email sending',
  'Receiving any kind of correspondance from her landlord',
  'Doors slamming',
  'Windows slamming',
  'Lights buzzing',
  'The sound of a phone falling to the ground',
  'The sound the toilet water made when she dropped her phone into it that one time',
  'The sound her laptop made when she pushed it off her desk that one time',
  'The sound a slug is made as it is crushed underfoot',
  'When someone asks her for directions',
  "When she knows she is about to meet someone new and she isn’t sure whether she should be shaking their hands or maybe even giving them a kiss on the cheek",
  'Whenever any ticket inspector asks her for a ticket, even though she always buys a ticket',
  'When she adds something to her online basket and the timer in the corner begins, that tells her she has increasingly little time to definitely buy this thing',
  "When she joins an online queue to buy tickets and she doesn't know how long this repetiton will continue",
  "When she is on hold and she doesn't know how long this repetition will continue",
  "Feeling trapped",
  "Feeling like nothing will change",
  "Having to make a decision",
  "Having to make a decision alone",
  "Having to make a decision under the gaze of other people",
  "Crowds",
  "Introspection",
  "The sound of her own chewing in a room with other people"
]

export default vibrations;